version: '3'

services:
  redmine:
    image: redmine
    restart: always
    ports: 
      - 8080:3000
    env_file: 
      - redmine.env
  
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8070:8080
